YESS/Models/ViewModel/PrescriptionsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using YESS.BE;

namespace YESS.Models.ViewModel
{
	public class PrescriptionsViewModel
	{
		//class of patient view model
		private Prescriptions current;

		public int Id
		{
			get { return current.Id; }
			set { current.Id = value; }
		}

		[DisplayName("תעודת זהות רופא")]
		public string ID_TZ_Doctor
		{
			get { return current.ID_TZ_Doctor; }
			set { current.ID_TZ_Doctor = value; }
		}
		[DisplayName("תעודת זהות פציינט")]
		public string ID_TZ_Patient
		{
			get { return current.ID_TZ_Patient; }
			set { current.ID_TZ_Patient = value; }
		}
		[DisplayName("התרופה NDC מזהה")]
		public string NDC
		{
			get { return current.NDC; }
			set { current.NDC = value; }
		}
		[DisplayName("תאריך התחלת לקיחת התרופה")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime Start
		{
			get { return current.Start; }
			set { current.Start = value; }
		}
		[DisplayName("תאריך סיום לקיחת התרופה")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime Last
		{
			get { return current.Last; }
			set { current.Last = value; }
		}
		[DisplayName("מספר פעמים לנטילת התרופה")]
		public string TimesToTake
		{
			get { return current.TimesToTake; }
			set { current.TimesToTake = value; }
		}// how many time and when to take the prescription
		[DisplayName("כמות מנה")]
		public string Ammount
		{
			get { return current.Ammount; }
			set { current.Ammount = value; }
		}// the amount of the drug to take every time

		public PrescriptionsViewModel(Prescriptions p)
		{
			this.current = p;
		}
	}
}

YESS/Controllers/PrescriptionsController.cs
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YESS.BE;

using YESS.Models;
using YESS.Models.ViewModel;

namespace YESS.Controllers
{
    public class PrescriptionsController : Controller
    {
        //return the view that ask for id in order to show its prescriptions
        public ActionResult DetailsAskForID()
        {
            CreatePrescriptionViewModel p = new CreatePrescriptionViewModel();
            return View("DetailsAskForID", p);
        }
        //recieves collection that contains id and send to function details
        [HttpPost]
        public ActionResult DetailsAskForID(FormCollection collection)
        {
            var _ID_TZ_Patient = collection["prescriptions.ID_TZ_Patient"];

            return Details(_ID_TZ_Patient);
        }

        // GET: Prescriptions/Details/5
        //recieves id and return the view with all patient prescriptions
        public ActionResult Details(string id)
        {
            PrescriptionsModel model = new PrescriptionsModel();
            PatientModel model2 = new PatientModel();
            var p = model2.GetPatientById(id);
            RouteConfig.pvm = p;
            var prescriptions = model.GetPrescriptionsByIdPatient(id);
            return View("Details", prescriptions);
        }
        // GET: Prescriptions/Create
        //return view that asks for id and ndc
        public ActionResult Create1()
        {

            CreatePrescriptionViewModel createPrescriptionViewModel = new CreatePrescriptionViewModel();
            return View("Create1", createPrescriptionViewModel);
        }

        // POST: Prescriptions/Create
        //recieves collection that contains id of patient and ndc and sent to function create 
        //checks the allow for prescription
        [HttpPost]
        public ActionResult Create1(FormCollection collection)
        {
            try
            {
                PrescriptionsModel model = new PrescriptionsModel();
                var _ID_TZ_Patient = collection["prescriptions.ID_TZ_Patient"];
                var _NDC = collection["medicine.PRODUCTNDC"];
                var start = Convert.ToDateTime( collection["Start"]);
                var last = Convert.ToDateTime( collection["Last"]);
              
                
                string x = model.getPrescriptionsAllow(_NDC, _ID_TZ_Patient,start, last);
                return Create(_ID_TZ_Patient, _NDC, x,start,last);

            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Prescriptions/Create
        //recieves id of patient and ndc it shows the string recieved
        //return the view to create prescription
        public ActionResult Create(string _ID_TZ_Patient, string NDC, string x, DateTime _startdate, DateTime _lastdate)
        {
            CreatePrescriptionViewModel createPrescriptionViewModel = new CreatePrescriptionViewModel();
            createPrescriptionViewModel.id = _ID_TZ_Patient;
            createPrescriptionViewModel.lastdate = _lastdate;
            createPrescriptionViewModel.startdate = _startdate;
            
            createPrescriptionViewModel.medicine.PRODUCTNDC = NDC;
            ViewBag.prescriptionsAllow1 = " תוצאות בדיקת ההתנגשויות בין המרשמים למטופל, ת.ז";
            ViewBag.prescriptionsAllow2 = _ID_TZ_Patient;
            ViewBag.prescriptionsAllow = x;
            RouteConfig.helper2 = 1;
            return View("Create", createPrescriptionViewModel);
        }

        // POST: Prescriptions/Create
        //recieve collection with all details and create prescription
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                PrescriptionsModel model = new PrescriptionsModel();
                DoctorModel model2 = new DoctorModel();
                var _ID_TZ_Doctor = RouteConfig.user.ID_TZ;
                var _ID_TZ_Patient = collection["id"];
                var _NDC = collection["medicine.PRODUCTNDC"];
                var start = collection["startdate"];
                var last = collection["lastdate"];
                var timesToTake = collection["TimesToTake"];
                var ammount = collection["Ammount"];
                RouteConfig.helper2 = 0;
                //בדיקות
              /*  if (_ID_TZ_Patient == "" || _NDC == "" || start == "" || last == "" || timesToTake == "" || ammount == "")
                {
                    RouteConfig.helper2 = 0;
                    ViewBag.succeessOrNot = "חסר נתונים, נסה שנית";
                    return View();

                }*/
               
                if (model2.DoctorExistent(_ID_TZ_Doctor))//_ID_TZ_Doctor פונקצי שבודקת קיימות של רופא לפי תז 

                {
                    List<string> answer = model.AddPrescriptions(_ID_TZ_Doctor, _ID_TZ_Patient, _NDC, Convert.ToDateTime(start), Convert.ToDateTime(last), timesToTake,
                                     ammount);
                    if (answer[3]== "המרשם נקלט בהצלחה במאגר המרשמים")
                    {
                        RouteConfig.pre = new Prescriptions();
                        RouteConfig.pre.Start =Convert.ToDateTime(start);
                        RouteConfig.pre.Last = Convert.ToDateTime(last);
                        RouteConfig.pre.TimesToTake = timesToTake;
                        RouteConfig.pre.Ammount = ammount;
                        RouteConfig.pre.NDC = _NDC;
                        RouteConfig.pre.ID_TZ_Doctor = _ID_TZ_Doctor ;
                        RouteConfig.pre.ID_TZ_Patient = _ID_TZ_Patient;


                    }
                    ViewBag.succeessOrNot1 = answer[0];
                    ViewBag.succeessOrNot2 = answer[1];
                    ViewBag.succeessOrNot3 = answer[2];
                    ViewBag.succeessOrNot4 = answer[3];
                    return View();
                }
                else
                {
                    Prescriptions p = new Prescriptions()
                    {
                        ID_TZ_Doctor = _ID_TZ_Doctor,
                        ID_TZ_Patient = _ID_TZ_Patient,
                        NDC = _NDC,
                        Start = Convert.ToDateTime(start),
                        Last = Convert.ToDateTime(last),
                        TimesToTake = timesToTake,
                        Ammount = ammount
                    };
                    return NotExist(p);

                }
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        //return the view to show errors
        public ActionResult NotExist(Prescriptions p)
        {
            return View("NotExist", p);
        }
        //return the home page view
        [HttpPost]
        public ActionResult NotExist()
        {
            return RedirectToAction("Index", "Home");
        }
        //return the view to show errors
        public ActionResult NotExist2()
        {
            return View("NotExist2");
        }
        
       //return view to ask for ndc
        public ActionResult DetailsAskForNCD()
        {
            CreatePrescriptionViewModel p = new CreatePrescriptionViewModel();
            return View("DetailsAskForNCD", p);
        }
        [HttpPost]
        //recieves collection that contains ndc and send to function DetailsNCD
        public ActionResult DetailsAskForNCD(FormCollection collection)
        {
            var _ndc = collection["prescriptions.NDC"];
            return DetailsNCD(_ndc);
        }

        // GET: Prescriptions/Details/5
        //recieves ndc and return the view with all prescriptions with this ndc
        public ActionResult DetailsNCD(string ndc)
        {
            PrescriptionsModel model = new PrescriptionsModel();
            List<Prescriptions> p = model.GetPrescriptionsByNdc(ndc);
            List<PrescriptionsViewModel> p2 = new List<PrescriptionsViewModel>();
            foreach (var item in p)
            {
                p2.Add(new PrescriptionsViewModel(item));
            }

            return View("DetailsNCD", p2);
        }
       



        public void CreateDocument()
        {
           

            DoctorModel md = new DoctorModel();
            var doc = md.GetDoctorById(RouteConfig.pre.ID_TZ_Doctor);
            PatientModel mp = new PatientModel();
            var pati = mp.GetPatientById(RouteConfig.pre.ID_TZ_Patient);
            MedicineModel m = new MedicineModel();
            var medicin = m.GetMedicineById(RouteConfig.pre.NDC);



            //Create an instance of PdfDocument.
            using (PdfDocument document = new PdfDocument())
            {
                //Add a page to the document
                PdfPage page = document.Pages.Add();

                //Create PDF graphics for the page
                PdfGraphics graphics = page.Graphics;
                string d = Convert.ToString(DateTime.Now);
                //Set the standard font
                PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 10);
                PdfFont font1 = new PdfStandardFont(PdfFontFamily.Helvetica, 8);
                PdfFont font2 = new PdfStandardFont(PdfFontFamily.Helvetica, 11);
                PdfFont font3 = new PdfStandardFont(PdfFontFamily.Helvetica, 15);

                //Load the image from the disk.
                PdfBitmap image = new PdfBitmap(Server.MapPath("~/img/logo3.png"));
                //Draw the image
                graphics.DrawImage(image, 0, 0);
                // Open the document in browser after saving it
                //Close the document.
                //Draw the text
                graphics.DrawString("Address: Aluf-David 187 Ramat-Gan, Israel", font, PdfBrushes.Black, new PointF(5, 45));

YESS/Views/Prescriptions/Create.cshtml
@model YESS.Models.CreatePrescriptionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item" style="text-align:right">
                        <h2>הנפקת מרשם</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@using (Html.BeginForm("Create", "Prescriptions", FormMethod.Post))
{

    <h2 style="text-align:center">@ViewBag.succeessOrNot</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.prescriptionsAllow1</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.prescriptionsAllow2</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.prescriptionsAllow</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.succeessOrNot1</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.succeessOrNot2</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.succeessOrNot3</h2>
    <br>
    <h2 style="text-align:center">@ViewBag.succeessOrNot4</h2>
    <br>
    <div style="text-align:center" dir="rtl">

        &nbsp;&nbsp;&nbsp;
        <a href='@Url.Action("Create1", "Prescriptions")' class="button button-contactForm btn_1">בדיקת התנגשות נוספת</a>

    </div>
    @Html.AntiForgeryToken()
    <div>
        @if (RouteConfig.helper2 == 1)
        {
            <div class="form-horizontal" style="text-align:right" dir="rtl">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.ID_TZ_Doctor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => RouteConfig.user.ID_TZ, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.EditorFor(model => RouteConfig.user.ID_TZ, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })
                        @Html.ValidationMessageFor(model => model.prescriptions.ID_TZ_Doctor, "", new { @class = "text-danger" })


                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.ID_TZ_Patient, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })
                        @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
                        
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.NDC, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.medicine.PRODUCTNDC, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.EditorFor(model => model.medicine.PRODUCTNDC, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })
                        @Html.ValidationMessageFor(model => model.medicine.PRODUCTNDC, "", new { @class = "text-danger" })
                        
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.Start, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.startdate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.EditorFor(model => model.startdate, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })
                        @Html.ValidationMessageFor(model => model.prescriptions.Start, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.Last, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                         @Html.EditorFor(model => model.lastdate, new { htmlAttributes = new { @class = "form-control" , @disabled = "disabled" } })
                        @Html.EditorFor(model => model.lastdate, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })
                         @Html.ValidationMessageFor(model => model.prescriptions.Last, "", new { @class = "text-danger" })
                       

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.TimesToTake, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        
                        <input required name="TimesToTake" type="number" class="form-control" min="1" id="TimesToTake">

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.prescriptions.Ammount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        
                        <input required  name="Ammount" type="number" class="form-control" id="Ammount" min="1" minlength="1">

                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="button button-contactForm btn_1">הנפקת מרשם</button>



                        <input type="reset" class="button button-contactForm btn_1">
                    </div>
                </div>
            </div>
        }
    </div>
}
@if (RouteConfig.helper2 == 0 && ViewBag.succeessOrNot4 == "המרשם נקלט בהצלחה במאגר המרשמים")
{
     <div style="text-align:right" dir="rtl">
         &nbsp;&nbsp;&nbsp;
         <a href='@Url.Action("CreateDocument", "Prescriptions")' class="button button-contactForm btn_1">הדפסת מרשם</a>
     
     </div>
}
<div style="text-align:right" dir="rtl">
    &nbsp;&nbsp;&nbsp;
    <a href='@Url.Action("Index", "Home")' class="button button-contactForm btn_1">חזרה לעמוד הראשי</a>

</div>

YESS/Views/Prescriptions/Create1.cshtml
@model YESS.Models.CreatePrescriptionViewModel

@{
    ViewBag.Title = "Create1";
    Layout = "~/Views/YESS_Layout.cshtml";
}
<script>
    function check_date() {
        var start = document.getElementById("Start").value;
        var end = document.getElementById("Last").value;
        if (start > end && end != '' && start != '') {
            alert("תאריך התחלה חייב להיות לפני תאריך סיום");
        }
    }
</script>
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item" style="text-align:right">

                        <h2> הנפקת מרשם </h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@using (Html.BeginForm("Create1", "Prescriptions", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    <h2 style="text-align:center" dir="rtl">@ViewBag.succeessOrNot</h2>
<div class="form-horizontal" style="text-align:right" dir="rtl">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.prescriptions.ID_TZ_Patient, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           
            @Html.DropDownListFor(model => model.prescriptions.ID_TZ_Patient, new SelectList(Model.tz, Model.prescriptions.ID_TZ_Patient), htmlAttributes: new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prescriptions.NDC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            
            @Html.DropDownListFor(model => model.medicine.PRODUCTNDC, new SelectList(Model.ndcs, Model.medicine.PRODUCTNDC), htmlAttributes: new { @class = "form-control" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.prescriptions.Start, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           
            <input required  name="Start" type="date" onchange="check_date()" class="form-control" min="@(DateTime.Now.ToString("yyyy-MM-dd"))" id="Start">

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.prescriptions.Last, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            
            <input required  name="Last" type="date" class="form-control" onchange="check_date()" min="@(DateTime.Now.ToString("yyyy-MM-dd"))" id="Last" >

        </div>
    </div>






    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="button button-contactForm btn_1">בדיקת התנגשויות</button>
        </div>
    </div>
</div>
        }

<div style="text-align:right" dir="rtl">
    &nbsp;&nbsp;&nbsp;
    <a href='@Url.Action("Index", "Home")' class="button button-contactForm btn_1">חזרה לעמוד הראשי</a>

</div>

YESS/Views/Prescriptions/Details.cshtml
@model IEnumerable<YESS.Models.ViewModel.PrescriptionsViewModel>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>פרטי מטופל והיסטוריית מרשמים</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<h2 style="text-align:right" dir="rtl">פרטי מטופל</h2>
<table class="table" dir="rtl" style="text-align:right">
    <tr>
        <th>
            <label>שם פרטי</label>
        </th>
        <th>
            <label>שם משפחה</label>
        </th>
        <th>
            <label>תעודת זהות</label>
        </th>
        <th>
            <label>מין</label>
        </th>
        <th>
            <label>כתובת</label>
        </th>
        <th>
            <label>מספר טלפון</label>
        </th>
        <th>
            <label>כתובת מייל</label>
        </th>
        <th>
            <label>תאריך לידה</label>
        </th>
        <th>
            <label>רקע רפואי</label>
        </th>
        <th>
            <label>אלרגיות</label>
        </th>
        
        <th></th>
    </tr>

   
        <tr>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.LasttName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.ID_TZ)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.BirthDate.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Hmo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => RouteConfig.pvm.Allergy)
            </td>
            
           
        </tr>

        </table>



   <h2 style="text-align:right" dir="rtl">היסטוריית מרשמים</h2>
        <table class="table" dir="rtl" style="text-align:right">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID_TZ_Doctor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ID_TZ_Patient)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NDC)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Start)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Last)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TimesToTake)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ammount)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_TZ_Doctor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_TZ_Patient)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NDC)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Start)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Last)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimesToTake)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ammount)
                    </td>

                </tr>
            }

        </table>
        <div class="form-group" dir="rtl" style="text-align:right">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("Index", "Home")' class="button button-contactForm btn_1">חזרה לעמוד הראשי</a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                <a href='@Url.Action("Create1", "Prescriptions")' class="button button-contactForm btn_1">הנפקת מרשם</a>

            </div>
        </div>

YESS/Views/Prescriptions/DetailsAskForID.cshtml
@model YESS.Models.CreatePrescriptionViewModel

@{
    ViewBag.Title = "DetailsAskForID";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>פרטי מטופל והיסטוריית מרשמים</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@using (Html.BeginForm("DetailsAskForID", "Prescriptions", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="text-align:right" dir="rtl">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.prescriptions.ID_TZ_Patient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                @Html.DropDownListFor(model => model.prescriptions.ID_TZ_Patient, new SelectList(Model.tz, Model.prescriptions.ID_TZ_Patient), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="button button-contactForm btn_1">צפיה בפרטים</button>

            </div>
        </div>
    </div>
}

<div style="text-align:right" dir="rtl">
    &nbsp;&nbsp;&nbsp;
    <a href='@Url.Action("Index", "Home")' class="button button-contactForm btn_1">חזרה לעמוד הראשי</a>

</div>

YESS/Views/Prescriptions/NotExist2.cshtml
@{
    ViewBag.Title = "NotExist2";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>שגיאה-הזנת נתונים שאינם קיימים</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<div style="text-align:right">
    <a href='@Url.Action("Index", "Home")' class="button button-contactForm btn_1">חזרה לעמוד הראשי</a>

</div>