YESS/Models/ViewModel/DoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using YESS.BE;

namespace YESS.Models
{
    public class DoctorViewModel
    {// class of doctor view model
		private Doctor current;

		public int Id
		{
			get { return current.Id; }
			set { current.Id = value; }
		}
		[DisplayName("מספר רישוי")]
		public string LicenseNumber
		{
			get { return current.LicenseNumber; }
			set { current.LicenseNumber = value; }
		}
		[DisplayName("שם פרטי")]
		public string FirstName
		{
			get { return current.FirstName; }
			set { current.FirstName = value; }
		}
		[DisplayName("שם משפחה")]
		public string LasttName
		{
			get { return current.LasttName; }
			set { current.LasttName = value; }
		}
		[DisplayName("שם באנגלית")]
		public string EnglishName
		{
			get { return current.EnglishName; }
			set { current.EnglishName = value; }
		}
		[DisplayName("מין")]
		public string Gender
		{
			get { return current.Gender; }
			set { current.Gender = value; }
		}
		[DisplayName("כתובת")]
		public string Address
		{
			get { return current.Address; }
			set { current.Address = value; }
		}
		[DisplayName("מספר טלפון")]
		public string Phone
		{
			get { return current.Phone; }
			set { current.Phone = value; }
		}
		[DisplayName("כתובת מייל")]
		public string Mail
		{
			get { return current.Mail; }
			set { current.Mail = value; }
		}
		[DisplayName("תאריך לידה")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime BirthDate
		{
			get { return current.BirthDate; }
			set { current.BirthDate = value; }
		}
		[DisplayName("תעודת זהות")]

		public string ID_TZ
		{
			get { return current.ID_TZ; }
			set { current.ID_TZ = value; } // the tehudat zehut 
		}
		[DisplayName("סיסמה")]
		public string Password
		{
			get { return current.Password; }
			set { current.Password = value; }
		}
		[DisplayName("שם משתמש")]

		public string UserName
		{
			get { return current.UserName; }
			set { current.UserName = value; }
		}
		[DisplayName("תחום התמחות")]

		public string TypeSpecial
		{
			get { return current.TypeSpecial; }
			set { current.TypeSpecial = value; }
		}

		public DoctorViewModel(Doctor p)
		{
			this.current = p;
		}
	}
}

YESS/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YESS.BE;
using YESS.Models;

namespace YESS.Controllers
{
    public class MedicineController : Controller
    {
        // GET: Medicine
        public ActionResult Index()
        {
            return View();
        }
        // GET: Medicine/Details/5
        //return the view of list of all medicines 
        public ActionResult DetailsForDocto()
        {
            MedicineModel model = new MedicineModel();
          var medicines = model.GetMedicinesWithImage();
            return View(medicines);
        }
        // GET: Medicine/Details/5
        //return the view of list of all medicines 
        public ActionResult Details()
        {
            MedicineModel model = new  MedicineModel();
            var medicines = model.GetMedicinesWithImage();
            return View(medicines);
        }
        #region C E D for image  

        // GET: Medicine/Create
        //return the view in order to recieve the ndc
        public ActionResult Create()
        {
            CreateMedicineViewModel createMedicineViewModel = new CreateMedicineViewModel(); 
            return View(createMedicineViewModel);
        }

        // POST: Medicine/Create
        //recieves collection that contains the ndc
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                MedicineModel model = new MedicineModel();
                var _PRODUCTNDC = collection["medicine.PRODUCTNDC"];
                return Create2(_PRODUCTNDC);
                //not suit the drug. if it true so it is ok and than the picture will add to the medicine in the db.
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        //recieves ndc and return the view to add image to the medicine
        public ActionResult Create2(string ndc)
        {
            RouteConfig.helper = ndc;
            RouteConfig.helper2 = 1;
            return View("Create2");
        }
        //recieves the file and upload it to google drive and saves the name of it in data base 
        [HttpPost]
        public ActionResult Create2(HttpPostedFileBase file)
        {
            RouteConfig.helper2 = 0;
            MedicineModel model = new MedicineModel();
            string result = model.AddImage(RouteConfig.helper, file);
            ViewBag.succeessOrNot = result;
            RouteConfig.helper = "";
            return View();
        }
        //return the view to recieve ndc
        public ActionResult Edit1()
        {
            CreateMedicineViewModel createMedicineViewModel = new CreateMedicineViewModel();
            return View(createMedicineViewModel);
        }
        // POST: Doctor/Edit1/5
        //recieves collection that contain ndc and send it to edit function
        [HttpPost]
        public ActionResult Edit1(FormCollection collection)
        {
            try
            {
                MedicineModel model = new MedicineModel();
                var NDC = collection["medicine.PRODUCTNDC"];
                 return Edit(NDC);
            }
            catch
            {
                return View();
            }
        }
      

        // GET: Medicine/Edit/5
        //recieves ndc and return the view in order to update the image
        public ActionResult Edit(string ndc)
        {
            MedicineModel model = new MedicineModel();
            var medicin = model.GetMedicineById(ndc);
            RouteConfig.helper = ndc;
            RouteConfig.helper2 = 1;
          if (medicin.Image == "")
            {
              return Create2(ndc);
            }
            return View("Edit", medicin);
        }
        

        // POST: Medicine/Edit/5
        //recieves the image and update the medicine image 
        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file)
        {
            try
            {
                RouteConfig.helper2 = 0;
               
                MedicineModel model = new MedicineModel();
                string answer = model.EditImage(RouteConfig.helper, file);
                RouteConfig.helper = "";
                ViewBag.succeessOrNot = answer;
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        //return help view to show error
        public ActionResult NotExist2()
        {
            return View("NotExist2");
        }

        // get: medicine/Delete1/5
        //return view to recieve ndc to delete image
        [HttpGet]
        public ActionResult Delete1()
        {
            CreateMedicineViewModel createMedicineViewModel = new CreateMedicineViewModel();
            return View(createMedicineViewModel);

        }
        // POST: medicine/Delete1/5
        //recieves collection that contains ndc and sends to delete impage
        [HttpPost]
        public ActionResult Delete1(FormCollection collection)
        {
            try
            {
                MedicineModel model = new MedicineModel();
                var ndc = collection["medicine.PRODUCTNDC"];
                return Delete(ndc);
            }
            catch
            {
                return View();
            }
        }


        // GET: Medicine/Delete/5
        //recieves ndc and reurn the view to delete image - ask for being sure to delete
        public ActionResult Delete(string ndc)
        {
            RouteConfig.helper2 = 1;
            MedicineModel model = new MedicineModel();
            var medicine = model.GetMedicineById(ndc);
            if (medicine.Image =="")
            {
               return NotExist2();
            }
            return View("Delete", medicine);
        }

        // POST: Medicine/Delete/5
        //recieves collection that contains ndc in order to delete image- delete it from drive and data base
        [HttpPost]
        public ActionResult Delete( FormCollection collection)
        {
            try
            {
                MedicineModel model = new MedicineModel();
                RouteConfig.helper2 = 0;
                var ndc = collection["PRODUCTNDC"];
                string answer = model.DeleteImage(ndc);
                ViewBag.succeessOrNot = answer;
                return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        #endregion

        #region full medicine


        // GET: Doctor/Create
        //return view to create medicine
        public ActionResult CreateMedicine()
        {
            Medicine m = new Medicine();
            RouteConfig.helper2 = 1;
            return View(m);
        }

        // POST: Doctor/Create
        //after submit create the medicine
        [HttpPost]
        public ActionResult CreateMedicine(FormCollection collection)
        {
            try
            {
                RouteConfig.helper2 = 0;
                MedicineModel model = new MedicineModel();
                var name = collection["Name"];
                var producer = collection["Producer"];
                var genericName = collection["GenericName"];
                var activeIngredients = collection["ActiveIngredients"];
                var dosageFormName = collection["DosageFormName"];
                var activeNumeratorStrength = collection["ACTIVE_NUMERATOR_STRENGTH"];
                var activeIngredUnit = collection["ACTIVE_INGRED_UNIT"];
                var ndc = collection["PRODUCTNDC"];
             /*   if (name==""|| producer == "" || genericName == "" || activeIngredients == "" || dosageFormName == "" || activeNumeratorStrength == "" || activeIngredUnit == "" || ndc == "" )
                {
                    RouteConfig.helper2 = 1;
                    ViewBag.succeessOrNot = "חסר נתונים, נסה שנית";
                    return View();
                }*/
                string answer = model.AddMedicine(name, producer, genericName, activeIngredients, dosageFormName,
                  activeNumeratorStrength, activeIngredUnit, ndc);
                ViewBag.succeessOrNot = answer;
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.succeessOrNot = "המטופל לא נכנס למאגר";
                return View();
            }
        }
        //return the view to ask for ndc for medicine to delete
        public ActionResult Delete1Medicine()
        {
            CreateMedicineViewModel createMedicineViewModel = new CreateMedicineViewModel();
            return View(createMedicineViewModel);

        }

        // POST: Medicine/Delete/5
        //recives ndc and send to delete the medicine
        [HttpPost]
        public ActionResult Delete1Medicine(FormCollection collection)
        {
            try
            {
                MedicineModel model = new MedicineModel();
                var ndc = collection["medicine.PRODUCTNDC"];
                return DeleteMedicine(ndc);

            }
            catch
            {
                return View();
            }
        }
        //recieves ndc and return the view with medicine details
        public ActionResult DeleteMedicine(string ndc)
        {
            RouteConfig.helper2 = 1;
            MedicineModel model = new MedicineModel();
            var m = model.GetMedicineById(ndc);
            return View("DeleteMedicine", m);
        }
        //recieves collection that contains ndc and delete medicine
        [HttpPost]
        public ActionResult DeleteMedicine(FormCollection collection)
        {
            try
            {
                RouteConfig.helper2 =0;
                MedicineModel model = new MedicineModel();
                var ndc = collection["PRODUCTNDC"];
                string answer = model.DeleteMedicine(ndc);

YESS/Controllers/ShowChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YESS.Models;

namespace YESS.Controllers
{
    public class ShowChartController : Controller
    {
        //return view that asks for ndc and year
        public ActionResult BeforeIndex()
        {
            ChartsViewModel x = new ChartsViewModel();
            return View(x);
        }
        // POST: Doctor/Edit/5
        //recieves collection that contains the year and ndc and send to function index
        [HttpPost]
        public ActionResult BeforeIndex(FormCollection collection)
        {
            try
            {
                DoctorModel model = new DoctorModel();
                var myYear = Convert.ToInt32(collection["MYyears"]);
                var ndc = collection["medicine.PRODUCTNDC"];
                return Index(ndc, myYear);
            }
            catch
            {
                return View();
            }
        }
        // GET: ShowChart
        //recieves ndc and year and show the Incidence of taking a medicine per year 
        public ActionResult Index(string ndc,int myYear)//שנה ותרופה ומציגה את השכיחות של לקיחת תרופה בשנה זאת לכלל הפציאנטים 
        {//רופא ואדמניסטרטור
            PrescriptionsModel prescriptionsModel = new PrescriptionsModel();
            var result = prescriptionsModel.ChartPrescriptionInOneYear(myYear, ndc);// לשנות פה כך שנקבל את השדה שהמשתמש הכניס
            return View("Index", result);

        }
        //recieves collection that contains the year and ndc
        public ActionResult BeforeIndex1()
        {
            ChartsViewModel x = new ChartsViewModel();
            return View(x);
        }


        // POST: Doctor/Edit/5
        //recieves collection that contains the year and ndc and send to function index1
        [HttpPost]
        public ActionResult BeforeIndex1(FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                DoctorModel model = new DoctorModel();
                var myYear = Convert.ToInt32(collection["MYyears"]);
                var ndc = collection["medicine.PRODUCTNDC"];
                return Index1(ndc, myYear);
            }
            catch
            {
                return View();
            }
        }
        //recieves ndc and year and show the prevalence of prescribing a drug per year 
        public ActionResult Index1(string ndc,int myYear)
        {
            PrescriptionsModel prescriptionsModel = new PrescriptionsModel();
            var result = prescriptionsModel.ChartStartPrescriptionInOneYear(myYear, ndc);// לשנות פה כך שנקבל את השדה שהמשתמש הכניס
            return View("Index1", result);

        }
        //recieves collection that contains the year and ndc
        public ActionResult BeforeIndex2()
        {
            ChartsViewModel x = new ChartsViewModel();
            return View(x);
        }


        // POST: Doctor/Edit/5
        //recieves collection that contains the year and ndc and send to function index2
        [HttpPost]
        public ActionResult BeforeIndex2(FormCollection collection)
        {
            try
            {
                DoctorModel model = new DoctorModel();
                var myYear = Convert.ToInt32(collection["MYyears"]);
                var ndc = collection["medicine.PRODUCTNDC"];
                return Index2(ndc, myYear);

            }
            catch
            {
                return View();
            }
        }
        //recieves ndc and year and show the incidence of taking a medicine in the selected year for all patients according to gender
        public ActionResult Index2(string ndc,int myYear)
        {
            PrescriptionsModel prescriptionsModel = new PrescriptionsModel();
            PrescriptionTwoListviewModel prescriptionTwoListviewModel = new PrescriptionTwoListviewModel(myYear, ndc);
            prescriptionTwoListviewModel.resultMale = prescriptionsModel.ChartPrescriptionInOneYear(myYear, ndc, "זכר");
            prescriptionTwoListviewModel.resultFemale = prescriptionsModel.ChartPrescriptionInOneYear(myYear, ndc, "נקבה");
            return View("Index2", prescriptionTwoListviewModel);
        }
        //for pie chart
        //return the view that shows the Distribution of patients by age
        public ActionResult Index3()
        {

            PatientModel patientModel = new PatientModel();
            var pieList = patientModel.AgeOfThePatients();
            return View("Index3", pieList);

        }

        //return the view that shows the distribution of doctors by field of specialization
        public ActionResult Index4()
        {

            DoctorModel doctorModel = new DoctorModel();
            var pieList = doctorModel.FieldDisciplineOfTheDoctor();
            return View("Index4", pieList);

        }


    }
}

YESS/Views/Home/Doctor.cshtml
@{
    ViewBag.Title = "Doctor";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>רופאים</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- breadcrumb start-->

<div class="form-group" dir="rtl" style="text-align:right">
    <div class="col-md-offset-2 col-md-10">
      
        <a href='@Url.Action("create", "Doctor")' class="button button-contactForm btn_1">הוספת רופא</a>
 
        <a href='@Url.Action("Edit1", "Doctor")' class="button button-contactForm btn_1">עדכון רופא</a>

        <a href='@Url.Action("Delete1", "Doctor")' class="button button-contactForm btn_1">מחיקת רופא</a>
        
        <a href='@Url.Action("Details", "Doctor")' class="button button-contactForm btn_1">מאגר רופאים</a>

    </div>


</div>




   

YESS/Views/Home/ForDoctor.cshtml
@{
    ViewBag.Title = "ForDoctor";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<body>

    <!-- breadcrumb start-->
    <section class="breadcrumb_part breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>אפשרויות</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->
    <div class="form-group" dir="rtl" style="text-align:right">
        <div class="col-md-offset-2 col-md-10">




            <a href='@Url.Action("DetailsForDoctor", "Patient")' class="button button-contactForm btn_1">מאגר מטופלים</a>




            <a href='@Url.Action("DetailsForDocto", "Medicine")' class="button button-contactForm btn_1">מאגר תרופות</a>




            <a href='@Url.Action("Create1", "Prescriptions")' class="button button-contactForm btn_1">הנפקת מרשם</a>







        <a href='@Url.Action("EditPatientHis", "Patient")' class="button button-contactForm btn_1">עדכון רקע רפואית ואלרגיה למטופל</a>


            <a href='@Url.Action("DetailsAskForID", "Prescriptions")' class="button button-contactForm btn_1">פרטי מטופל על פי ת.ז</a>


        </div>


    <!-- jquery plugins here-->

    <script src="~/js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="~/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- owl carousel js -->
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <!-- contact js -->
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.form.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/contact.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
</body>

YESS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<h2></h2>
<section class="banner_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-xl-5">
                <div class="banner_text">
                    <div class="banner_text_iner">
                        @if (RouteConfig.isUser == false)
                        {
                            <div style="text-align:left" dir="rtl">
                                <a href='@Url.Action("Mypass", "Home")' class="button button-contactForm btn_1">התחברות</a>

                            </div>

                        }
                        else
                        {
                            var x = "ברוך הבא" + " " + RouteConfig.user.FirstName + " " + RouteConfig.user.LasttName;
                            <h3><b> @x </b></h3>
                        }
                        <h3 dir="rtl">אנחנו כאן בשבילך</h3>
                        <h1>
                            Best Care &
                            Better Doctor
                        </h1>
                        <h3 dir="rtl">
                            אתר לרופא ולמזכירות
                        </h3>


                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner_img">
                    <img src="img/banner_img.png" alt="">
                </div>
            </div>
        </div>
    </div>
</section>

YESS/Views/Home/Medicine.cshtml
@{
    ViewBag.Title = "Medicine";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<body>

    <!-- breadcrumb start-->
    <section class="breadcrumb_part breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                  <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>תרופות</h2>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- breadcrumb start-->

    <div class="form-group" dir="rtl" style="text-align:right">

        <div class="col-md-offset-2 col-md-10">

          <a href='@Url.Action("CreateMedicine", "Medicine")' class="button button-contactForm btn_1">הוספה </a>
            <a href='@Url.Action("Delete1Medicine", "Medicine")' class="button button-contactForm btn_1">הסרה</a>

            <a href='@Url.Action("pageEdit", "Home")' class="button button-contactForm btn_1">עדכונים</a>

          <a href='@Url.Action("DetailsAskForNCD", "Prescriptions")' class="button button-contactForm btn_1">מרשמים על פי תרופה נבחרת</a>
            <a href='@Url.Action("Details", "Medicine")' class="button button-contactForm btn_1">מאגר תרופות</a>

        </div>





    </div>

    <!-- jquery plugins here-->



    <script src="~/js/jquery-1.12.1.min.js"></script>

    <!-- popper js -->

    <script src="~/js/popper.min.js"></script>

    <!-- bootstrap js -->

    <script src="~/js/bootstrap.min.js"></script>

    <!-- owl carousel js -->

    <script src="~/js/owl.carousel.min.js"></script>

    <script src="~/js/jquery.nice-select.min.js"></script>

    <!-- contact js -->

    <script src="~/js/jquery.ajaxchimp.min.js"></script>

    <script src="~/js/jquery.form.js"></script>

    <script src="~/js/jquery.validate.min.js"></script>

    <script src="~/js/mail-script.js"></script>

    <script src="~/js/contact.js"></script>

    <!-- custom js -->

    <script src="~/js/custom.js"></script>

</body>

YESS/Views/Home/Patient.cshtml
@{
    ViewBag.Title = "Patient";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<body>

    <!-- breadcrumb start-->
    <section class="breadcrumb_part breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>מטופלים</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <div class="form-group" dir="rtl" style="text-align:right">
        <div class="col-md-offset-2 col-md-10">

            <a href='@Url.Action("create", "Patient")' class="button button-contactForm btn_1">הוספת מטופל</a>

            <a href='@Url.Action("Edit1", "Patient")' class="button button-contactForm btn_1">עדכון מטופל</a>

            <a href='@Url.Action("Delete1", "Patient")' class="button button-contactForm btn_1">מחיקת מטופל</a>

            <a href='@Url.Action("DetailsAskForID", "Prescriptions")' class="button button-contactForm btn_1">הסטוריית מרשמי מטופל על פי ת.ז</a>

           <a href='@Url.Action("Details", "Patient")' class="button button-contactForm btn_1">מאגר מטופלים</a>

        </div>


    </div>

    <!-- jquery plugins here-->

    <script src="~/js/jquery-1.12.1.min.js"></script>

    <!-- popper js -->

    <script src="~/js/popper.min.js"></script>

    <!-- bootstrap js -->

    <script src="~/js/bootstrap.min.js"></script>

    <!-- owl carousel js -->

    <script src="~/js/owl.carousel.min.js"></script>

    <script src="~/js/jquery.nice-select.min.js"></script>

    <!-- contact js -->

    <script src="~/js/jquery.ajaxchimp.min.js"></script>

    <script src="~/js/jquery.form.js"></script>

    <script src="~/js/jquery.validate.min.js"></script>

    <script src="~/js/mail-script.js"></script>

    <script src="~/js/contact.js"></script>

    <!-- custom js -->

    <script src="~/js/custom.js"></script>

</body>

YESS/Views/Home/midgam.cshtml
@{
    ViewBag.Title = "midgam";
    Layout = "~/Views/YESS_Layout.cshtml";
}

<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2> מדגמים YESS</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- breadcrumb start-->

<div class="form-group" dir="rtl" style="text-align:right">
    <div class="col-md-offset-2 col-md-10">
        
        <a href='@Url.Action("BeforeIndex", "ShowChart")' class="button button-contactForm btn_1">לקיחת תרופה בשנה הנבחרת </a>
        <a href='@Url.Action("BeforeIndex1", "ShowChart")' class="button button-contactForm btn_1"> הנפקת מרשם בשנה נבחרת</a>
        <a href='@Url.Action("BeforeIndex2", "ShowChart")' class="button button-contactForm btn_1">לקיחת תרופה בשנה הנבחרת לפי מגדר</a>
       @if (RouteConfig.WhichUser == 1)
       {
        <a href='@Url.Action("Index3", "ShowChart")' class="button button-contactForm btn_1">התפלגות מטופלים לפי גיל</a>
        <a href='@Url.Action("Index4", "ShowChart")' class="button button-contactForm btn_1">התפלגות רופאים לפי תחום התמחות</a>
       }


    </div>


</div>

YESS/Views/Home/pageEdit.cshtml
@{
    ViewBag.Title = "pageEdit";
    Layout = "~/Views/YESS_Layout.cshtml";
}


<!-- breadcrumb start-->
<section class="breadcrumb_part breadcrumb_bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h2>עדכונים</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- breadcrumb start-->

<div class="form-group" dir="rtl" style="text-align:right">
    <div class="col-md-offset-2 col-md-10">

        <a href='@Url.Action("Edit1Medicine", "Medicine")' class="button button-contactForm btn_1">עדכון פרטי תרופה</a>

        <a href='@Url.Action("Edit1", "Medicine")' class="button button-contactForm btn_1">עדכון תמונה לתרופה</a>

        <a href='@Url.Action("Delete1", "Medicine")' class="button button-contactForm btn_1">מחיקת תמונה לתרופה</a>

    </div>


</div>